# Generated by Django 3.2 on 2022-01-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220131_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Ctaegories'},
        ),
    ]
